<?xml version="1.0" ?>
<robot name="scara_arm" xmlns:xacro="http://www.ros.org/wiki/xacro">



    <material name="red">
        <color rgba="0.5 0 0 1" />
    </material>

    <material name="green">
        <color rgba="0 0.5 0 1" />
    </material>

    <material name="blue">
        <color rgba="0 0 0.5 1" />
    </material>

    <material name="yellow">
        <color rgba="1 1 0 1" />
    </material>

    <material name="black">
        <color rgba="0 0 0 1" />
    </material>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>



  <link name="world"/>
  
  <!-- Connect world to your existing base_link -->
  <joint name="world_joint" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>





  <!-- base_link -->
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder length="${base_length}" radius="${base_radius}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0.005"/>
      <material name="red" />
    </visual>
    <collision>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_length}" />
            </geometry>
            <origin xyz="0 0 0.005" rpy="0 0 0" />
    </collision>
    <xacro:cylinder_inertia m="5.0" r="${base_radius}" l="${base_length}" 
                                xyz="0 0 0.005" rpy="0 0 0" />
  </link>


  
  <!-- link1 -->
  <link name="link1">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0.4"/>
      <geometry>
        <cylinder length="${link_1_length}" radius="${link_1_radius}"/>
      </geometry>
      <material name="green" />
    </visual>
    <collision>
            <geometry>
               <cylinder length="${link_1_length}" radius="${link_1_radius}"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0.4"/>
    </collision>
    <xacro:cylinder_inertia m="1.0" r="${link_1_radius}" l="${link_1_length}" 
                                xyz="0 0 0.4" rpy="0 0 0" />
  </link>


  
  
  
  
  
  

  <joint name="joint1" type="revolute">
    <parent link="base_link"/>
    <child link="link1"/>
    <origin rpy="0 0 0" xyz="0 0 0.01"/>
    <axis xyz="0 0 1"/>
    <limit effort="10" lower="-${pi}" upper="${pi}" velocity="10"/>
  </joint>


  <transmission name="joint1_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="joint1">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="motor1">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
   </transmission>



  <!-- link2 -->
  <link name="link2">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 -0.25"/>
      <geometry>
        <cylinder length="${arm_length}" radius="${arm_radius}"/>
      </geometry>
      <material name="blue" />
    </visual>
    <collision>
            <geometry>
               <cylinder length="${arm_length}" radius="${arm_radius}"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 -0.25"/>
    </collision>
    <xacro:cylinder_inertia m="1.0" r="${arm_radius}" l="${arm_length}" 
                                xyz="0 0 -0.25" rpy="0 0 0" />
  </link>


  


  <joint name="joint2" type="prismatic">
    <parent link="link1"/>
    <child link="link2"/>
    <origin rpy="0 0 0" xyz="0 0 0.8"/>
    <axis xyz="0 0 1"/>
    <limit effort="10" lower="0" upper="0.5" velocity="1"/>
  </joint>


  <transmission name="joint2_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="joint2">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="motor2">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
   </transmission>

  
  <!-- link3 -->
  <link name="link3">
    <visual>

      <origin rpy="0 0 0" xyz="0 0 0.25"/>
      <geometry>
        <cylinder length="${arm_length}" radius="${arm_radius}" />
      </geometry>
      <material name="yellow" />
    </visual>
    <collision>
            <geometry>
               <cylinder length="${arm_length}" radius="${arm_radius}"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0.25"/>
    </collision>
    <xacro:cylinder_inertia m="1.0" r="${arm_radius}" l="${arm_length}" 
                                xyz="0 0 0.25" rpy="0 0 0" />
  </link>


  


  <joint name="joint3" type="prismatic">
    <parent link="link2"/>
    <child link="link3"/>

    <origin rpy="${pi/2} 0 0" xyz="0 0.5 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="10" lower="0.0" upper="0.5" velocity="1"/>
  </joint>


   <transmission name="joint3_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint3">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


 <!-- link4 -->
  <link name="link4">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${link_4_length}" radius="${link_4_radius}" />
      </geometry>
      <material name="white" />
    </visual>
    <collision>
            <geometry>
               <cylinder length="${link_4_length}" radius="${link_4_radius}"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>
    <xacro:cylinder_inertia m="1.0" r="${link_4_radius}" l="${link_4_length}" 
                                xyz="0 0 0" rpy="0 0 0" />
  </link>


  


  <joint name="joint4" type="revolute">
    <parent link="link3"/>
    <child link="link4"/>
    <origin rpy="0 0 0" xyz="0 0 -0.05"/>
    <axis xyz="0 0 1"/>
    <limit effort="10" lower="-${pi}" upper="${pi}" velocity="1"/>
  </joint>


   <transmission name="joint4_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint4">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor4">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  


  <!-- link5 -->
  <link name="link5">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder radius="${link_5_radius}" length="${link_5_length}" />
      </geometry>
      <material name="red" />
    </visual>
    <collision>
            <geometry>
               <cylinder length="${link_5_length}" radius="${link_5_radius}"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>
    <xacro:cylinder_inertia m="1.0" r="${link_5_radius}" l="${link_5_length}" 
                                xyz="0 0 0" rpy="0 0 0" />
  </link>
  <joint name="joint5" type="fixed">
    <parent link="link4"/>
    <child link="link5"/>
    <origin rpy="0 0 0" xyz="0 0 -0.05"/>
  </joint>



  <!-- link6 -->
  <link name="link6">
    <visual>

      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${link_6_length}" radius="${link_6_radius}" />
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1" />
      </material>
    </visual>
    <collision>
            <geometry>
               <cylinder length="${link_6_length}" radius="${link_6_radius}"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>
    <xacro:cylinder_inertia m="1.0" r="${link_6_radius}" l="${link_6_length}" 
                                xyz="0 0 0.0" rpy="0 0 0" />
  </link>


  



  <joint name="joint6" type="revolute">
    <parent link="link5"/>
    <child link="link6"/>
    <axis xyz="0 0 1"/>
    <limit effort="10" lower="-${pi*3/4}" upper="${pi*3/4}" velocity="1"/>
    <origin rpy="${pi/2} 0 0" xyz="0 0 ${-link_5_length/2}"/>
  </joint>


   <transmission name="joint6_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint6">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor6">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
   </transmission>

  <!-- link7 -->
  <link name="link7">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder radius="${link_5_radius}" length="${link_5_length}" />
      </geometry>
      <material name="red" />
    </visual>
    <collision>
            <geometry>
               <cylinder length="${link_5_length}" radius="${link_5_radius}"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>
    <xacro:cylinder_inertia m="1.0" r="${link_5_radius}" l="${link_5_length}" 
                                xyz="0 0 0" rpy="0 0 0" />
  </link>
  <joint name="joint7" type="fixed">
    <parent link="link6"/>
    <child link="link7"/>
    <origin rpy="${-pi/2} 0 0" xyz="0 ${-link_5_length/2} 0"/>
  </joint>





  <!-- link8 -->
  <link name="link8">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${link_4_length}" radius="${link_4_radius}" />
      </geometry>
      <material name="white" />
    </visual>
    <collision>
            <geometry>
               <cylinder length="${link_4_length}" radius="${link_4_radius}"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>
    <xacro:cylinder_inertia m="1.0" r="${link_4_radius}" l="${link_4_length}" 
                                xyz="0 0 0" rpy="0 0 0" />
  </link>


  


  <joint name="joint8" type="revolute">
    <parent link="link7"/>
    <child link="link8"/>
    <origin rpy="0 0 0" xyz="0 0 -0.05"/>
    <axis xyz="0 0 1"/>
    <limit effort="10" lower="-${pi}" upper="${pi}" velocity="1"/>
  </joint>


  <transmission name="joint8_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint8">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor8">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
   </transmission>


  <!-- gripper_base -->
    <link name="gripper_base">
      <visual>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
          <box size="0.04 0.04 0.01"/>
          </geometry>
          <material name="gray">
          <color rgba="0.5 0.5 0.5 1"/>
          </material>
      </visual>
    </link>

    <joint name="joint_gripper_base" type="fixed">
      <parent link="link8"/>
      <child link="gripper_base"/>
      <origin xyz="0 0 ${-link_4_radius}" rpy="0 0 0"/>
    </joint>


    <!-- gripper_left_finger -->
    <link name="gripper_left_finger">
      <visual>
          <origin xyz="0 0.01 0" rpy="0 0 0"/>
          <geometry>
            <box size="0.02 0.02 0.15"/>
          </geometry>
          <material name="red">
            <color rgba="1 0 0 1"/>
          </material>
      </visual>
    </link>

    <joint name="joint_left_finger" type="fixed">
      <parent link="gripper_base"/>
      <child link="gripper_left_finger"/>
      <origin xyz="0 0.02 ${-link_4_radius}" rpy="0 0 0"/>
    </joint>

    <!-- gripper_right_finger -->
    <link name="gripper_right_finger">
      <visual>
          <origin xyz="0 -0.01 0" rpy="0 0 0"/>
          <geometry>
             <box size="0.02 0.02 0.15"/>
          </geometry>
          <material name="red">
        	  <color rgba="1 0 0 1"/>
	        </material>
      </visual>
    </link>

    <joint name="joint_right_finger" type="fixed">
      <parent link="gripper_base"/>
      <child link="gripper_right_finger"/>
      <origin xyz="0 -0.02 ${-link_4_radius}" rpy="0 0 0"/>
    </joint>


  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/scara_arm</robotNamespace>
      <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
    </plugin>
  </gazebo>

  
</robot>
